# Alphabetical Ordering Configuration
# Sorts modes alphabetically within each category

strategy: alphabetical

# Optional: Prioritize specific modes at the beginning
priority_modes:
  - code
  - debug

# Optional: Exclude specific modes
exclude_modes: []

# Categories will be processed in order: core → enhanced → specialized → discovered
# Within each category, modes are sorted alphabetically