# Category-Based Ordering Configuration
# Custom category precedence with specialized tools first

strategy: category

# Custom category order - specialized tools first, then core workflow
category_order:
  - specialized      # Tools like prompt-enhancer, conport-maintenance
  - core            # Essential workflow modes
  - enhanced        # Enhanced variants
  - discovered      # Any other modes

# How to sort within each category
within_category_sort: manual

# Manual ordering within specific categories
manual_category_order:
  core:
    - code           # Development first
    - architect      # Planning second  
    - debug          # Debugging third
    - ask            # Questions fourth
    - orchestrator   # Coordination last
  specialized:
    - prompt-enhancer           # Prompt enhancement first
    - conport-maintenance       # Maintenance second
    - prompt-enhancer-isolated  # Isolated tools last

# Priority modes (applied after category/manual ordering)
priority_modes: []

# Exclude modes
exclude_modes: []